<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartRoster.Application\SmartRoster.Application.csproj" />
    <ProjectReference Include="..\SmartRoster.infrastructure\SmartRoster.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartRoster.Shared\SmartRoster.Shared.csproj" />
  </ItemGroup>

</Project>
